server:
  port: 8082

spring:
  # БД (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/product_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver # Порт приложения

  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update                                    # Автосоздание/обновление схемы БД
    show-sql: true                                        # Логировать SQL‑запросы в консоль
    properties:
      hibernate:
        format_sql: true                                  # Форматировать SQL для читаемости
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms                                      # Таймаут подключения

  # Liquibase (если используете)
  liquibase:
    enabled: true
    change-log: classpath:db/db.changelog-master.yaml

# Логирование
logging:
  level:
    org.springframework: INFO
    com.ecommerce: DEBUG